name: Build Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: yarn
    - run: |
        echo ">>> Start compile nextchat."
        yarn run build
        echo ">>> Compile nextchat sucess!"
